services:
  - type: web
    name: agrisathi-backend
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DB_URL
        fromDatabase:
        name: agrisathidb
        property: connectionString
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DDL_AUTO
        value: validate
      - key: JWT_SECRET
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-vercel-domain.vercel.app
      - key: PORT
        value: "8080"
